<?xml version="1.0" ?>
<robot name="rosoomba" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="package_path" value="$(find rosoomba_description)" />

  <xacro:include filename="${package_path}/urdf/params.xacro" />

  <xacro:include filename="${package_path}/urdf/rosoomba_core.xacro" />
   
  <xacro:include filename="${package_path}/urdf/wheel.xacro" />
  <xacro:create_wheel prefix="left" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
  <xacro:create_wheel prefix="right" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>

  <!-- <xacro:include filename="${package_path}/urdf/gazebo_control.xacro" /> -->

  <xacro:include filename="${package_path}/urdf/ros2_control.xacro" />

</robot>
